from config.settings.base import *

DEBUG = False

# SESSION
SESSION_COOKIE_SECURE = True

# CSRF
CSRF_COOKIE_SECURE = True

# SECURITY MIDDLEWARE
SECURE_HSTS_SECONDS = 31536000  # 365 * 24 * 60 * 60
SECURE_HSTS_PRELOAD = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_SSL_REDIRECT = True
SECURE_REFERRER_POLICY = 'same-origin'
