version : '3'
services:
  nginx:
  api:
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    depends_on:
      - postgres
      - rabbitmq
  postgres:
    image: django-rest-framework-boilerplate/postgres
    build:
      context: postgres
      dockerfile: Dockerfile
    container_name: postgres
    ports:
      - '25432:5432'
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=Pass1@3
      - POSTGRES_DB=postgres_db
  rabbitmq:
    image: django-rest-framework-boilerplate/rabbitmq
    build:
      context: rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=Pass1@3
  celery-worker:
    image: django-rest-framework-boilerplate/celery-worker
    build:
      context: ./project
      dockerfile: Dockerfile
    container_name: celery-worker
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - IS_CELERY_WORKER=true
    depends_on:
      - api
      - postgres
      - rabbitmq
    restart: on-failure
