version : '2'
services:
  api:
    image: django-rest-framework-boilerplate/api
    build:
      context: ./project_name
      dockerfile : Dockerfile
    container_name: api
    command: gunicorn project_name.wsgi:application --bind 0.0.0.0:8000
    ports:
      - '8000:8000'
