version : '3'
services:
  custom-nginx:
  api:
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    depends_on:
      - db
      - rabbitmq
  db:
    image: postgres
    build:
      context: postgresql
      dockerfile: Dockerfile
    container_name: project_db
    ports:
      - '25432:5432'
    environment:
      - POSTGRES_USER=project_user
      - POSTGRES_PASSWORD=Pass1@3
      - POSTGRES_DB=project_db
  rabbitmq:
    build:
      context: rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=Pass1@3
  celery_worker:
    image: django-rest-framework-boilerplate/celery
    build:
      context: ./project
      dockerfile: Dockerfile
    container_name: celery_worker
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - IS_CELERY_WORKER=true
    depends_on:
      - api
      - db
      - rabbitmq
    restart: on-failure
