version : '3'
services:
  custom-nginx:
  api:
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
  db:
    image: postgres
    build:
      context: postgresql
      dockerfile: Dockerfile
    container_name: project_db
    ports:
      - '25432:5432'
    environment:
      - POSTGRES_USER=project_user
      - POSTGRES_PASSWORD=Pass1@3
      - POSTGRES_DB=project_db
